language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test

after_script:
  - COVERALLS_REPO_TOKEN=$repo_token
  - yarn coveralls
