language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules
env:
  global:
    CC_TEST_REPORTER_ID=$repo_token

install:
  - yarn install

script:
  - yarn add coveralls
  - yarn test

after_script:
  - COVERALLS_REPO_TOKEN=$repo_token
